/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
/**
 * Generated by vite-css-modules
 * https://npmjs.com/vite-css-modules
 */

declare const colour: string;
declare const colourName: string;
declare const swatches: string;
declare const swatch: string;
declare const toneLabel: string;

export {
	colour,
	colourName,
	swatches,
	swatch,
	toneLabel
};

declare const __default_export__: {
	colour: typeof colour;
	colourName: typeof colourName;
	swatches: typeof swatches;
	swatch: typeof swatch;
	toneLabel: typeof toneLabel;
};
export default __default_export__;
