/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
/**
 * Generated by vite-css-modules
 * https://npmjs.com/vite-css-modules
 */

declare const form: string;
declare const row: string;
declare const wheelCol: string;
declare const slidersCol: string;
declare const field: string;
declare const fieldRow: string;
declare const label: string;
declare const slider: string;
declare const value: string;
declare const colourInput: string;
declare const colourInvalid: string;
declare const nameRow: string;
declare const nameInput: string;
declare const addButton: string;
declare const error: string;

export {
	form,
	row,
	wheelCol,
	slidersCol,
	field,
	fieldRow,
	label,
	slider,
	value,
	colourInput,
	colourInvalid,
	nameRow,
	nameInput,
	addButton,
	error
};

declare const __default_export__: {
	form: typeof form;
	row: typeof row;
	wheelCol: typeof wheelCol;
	slidersCol: typeof slidersCol;
	field: typeof field;
	fieldRow: typeof fieldRow;
	label: typeof label;
	slider: typeof slider;
	value: typeof value;
	colourInput: typeof colourInput;
	colourInvalid: typeof colourInvalid;
	nameRow: typeof nameRow;
	nameInput: typeof nameInput;
	addButton: typeof addButton;
	error: typeof error;
};
export default __default_export__;
