/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
/**
 * Generated by vite-css-modules
 * https://npmjs.com/vite-css-modules
 */

declare const wrapper: string;
declare const label: string;
declare const labelText: string;
declare const labelValue: string;
declare const trackWrapper: string;
declare const track: string;
declare const input: string;

export {
	wrapper,
	label,
	labelText,
	labelValue,
	trackWrapper,
	track,
	input
};

declare const __default_export__: {
	wrapper: typeof wrapper;
	label: typeof label;
	labelText: typeof labelText;
	labelValue: typeof labelValue;
	trackWrapper: typeof trackWrapper;
	track: typeof track;
	input: typeof input;
};
export default __default_export__;
