/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
/**
 * Generated by vite-css-modules
 * https://npmjs.com/vite-css-modules
 */

declare const grid: string;
declare const swatch: string;
declare const dot: string;
declare const active: string;
declare const label: string;

export {
	grid,
	swatch,
	dot,
	active,
	label
};

declare const __default_export__: {
	grid: typeof grid;
	swatch: typeof swatch;
	dot: typeof dot;
	active: typeof active;
	label: typeof label;
};
export default __default_export__;
