/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
/**
 * Generated by vite-css-modules
 * https://npmjs.com/vite-css-modules
 */

declare const modal: string;
declare const header: string;
declare const title: string;
declare const close: string;
declare const body: string;

export {
	modal,
	header,
	title,
	close,
	body
};

declare const __default_export__: {
	modal: typeof modal;
	header: typeof header;
	title: typeof title;
	close: typeof close;
	body: typeof body;
};
export default __default_export__;
