/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
/**
 * Generated by vite-css-modules
 * https://npmjs.com/vite-css-modules
 */

declare const wrapper: string;
declare const svg: string;
declare const ring: string;
declare const indicator: string;
declare const focusRing: string;
declare const srOnly: string;

export {
	wrapper,
	svg,
	ring,
	indicator,
	focusRing,
	srOnly
};

declare const __default_export__: {
	wrapper: typeof wrapper;
	svg: typeof svg;
	ring: typeof ring;
	indicator: typeof indicator;
	focusRing: typeof focusRing;
	srOnly: typeof srOnly;
};
export default __default_export__;
