/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
/**
 * Generated by vite-css-modules
 * https://npmjs.com/vite-css-modules
 */

declare const wrapper: string;
declare const svg: string;
declare const indicator: string;

export {
	wrapper,
	svg,
	indicator
};

declare const __default_export__: {
	wrapper: typeof wrapper;
	svg: typeof svg;
	indicator: typeof indicator;
};
export default __default_export__;
