/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
/**
 * Generated by vite-css-modules
 * https://npmjs.com/vite-css-modules
 */

declare const header: string;
declare const wordmark: string;
declare const repoLink: string;
declare const repoIcon: string;

export {
	header,
	wordmark,
	repoLink,
	repoIcon
};

declare const __default_export__: {
	header: typeof header;
	wordmark: typeof wordmark;
	repoLink: typeof repoLink;
	repoIcon: typeof repoIcon;
};
export default __default_export__;
