/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
/**
 * Generated by vite-css-modules
 * https://npmjs.com/vite-css-modules
 */

declare const header: string;
declare const wordmark: string;

export {
	header,
	wordmark
};

declare const __default_export__: {
	header: typeof header;
	wordmark: typeof wordmark;
};
export default __default_export__;
