/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
/**
 * Generated by vite-css-modules
 * https://npmjs.com/vite-css-modules
 */

declare const tabs: string;
declare const tab: string;
declare const tabActive: string;

export {
	tabs,
	tab,
	tabActive
};

declare const __default_export__: {
	tabs: typeof tabs;
	tab: typeof tab;
	tabActive: typeof tabActive;
};
export default __default_export__;
