/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
/**
 * Generated by vite-css-modules
 * https://npmjs.com/vite-css-modules
 */

declare const bar: string;
declare const barHeader: string;
declare const toggle: string;
declare const toggleIcon: string;
declare const toggleLabel: string;
declare const copyButton: string;
declare const codeBlock: string;

export {
	bar,
	barHeader,
	toggle,
	toggleIcon,
	toggleLabel,
	copyButton,
	codeBlock
};

declare const __default_export__: {
	bar: typeof bar;
	barHeader: typeof barHeader;
	toggle: typeof toggle;
	toggleIcon: typeof toggleIcon;
	toggleLabel: typeof toggleLabel;
	copyButton: typeof copyButton;
	codeBlock: typeof codeBlock;
};
export default __default_export__;
