/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
/**
 * Generated by vite-css-modules
 * https://npmjs.com/vite-css-modules
 */

declare const wrapper: string;
declare const row: string;
declare const toneSlot: string;
declare const dotRow: string;
declare const dot: string;
declare const dotEmpty: string;
declare const dotSeeded: string;
declare const dotUser: string;
declare const swatch: string;
declare const swatchAnchored: string;
declare const swatchActive: string;
declare const toneLabel: string;
declare const toneLabelVisible: string;

export {
	wrapper,
	row,
	toneSlot,
	dotRow,
	dot,
	dotEmpty,
	dotSeeded,
	dotUser,
	swatch,
	swatchAnchored,
	swatchActive,
	toneLabel,
	toneLabelVisible
};

declare const __default_export__: {
	wrapper: typeof wrapper;
	row: typeof row;
	toneSlot: typeof toneSlot;
	dotRow: typeof dotRow;
	dot: typeof dot;
	dotEmpty: typeof dotEmpty;
	dotSeeded: typeof dotSeeded;
	dotUser: typeof dotUser;
	swatch: typeof swatch;
	swatchAnchored: typeof swatchAnchored;
	swatchActive: typeof swatchActive;
	toneLabel: typeof toneLabel;
	toneLabelVisible: typeof toneLabelVisible;
};
export default __default_export__;
