/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
/**
 * Generated by vite-css-modules
 * https://npmjs.com/vite-css-modules
 */

declare const wrapper: string;
declare const toneSlot: string;
declare const anchored: string;
declare const swatch: string;
declare const active: string;
declare const toneLabel: string;

export {
	wrapper,
	toneSlot,
	anchored,
	swatch,
	active,
	toneLabel
};

declare const __default_export__: {
	wrapper: typeof wrapper;
	toneSlot: typeof toneSlot;
	anchored: typeof anchored;
	swatch: typeof swatch;
	active: typeof active;
	toneLabel: typeof toneLabel;
};
export default __default_export__;
