/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
/**
 * Generated by vite-css-modules
 * https://npmjs.com/vite-css-modules
 */

declare const picker: string;
declare const colourInput: string;
declare const invalid: string;
declare const row: string;
declare const wheelCol: string;
declare const slidersCol: string;
declare const actions: string;
declare const removeButton: string;

export {
	picker,
	colourInput,
	invalid,
	row,
	wheelCol,
	slidersCol,
	actions,
	removeButton
};

declare const __default_export__: {
	picker: typeof picker;
	colourInput: typeof colourInput;
	invalid: typeof invalid;
	row: typeof row;
	wheelCol: typeof wheelCol;
	slidersCol: typeof slidersCol;
	actions: typeof actions;
	removeButton: typeof removeButton;
};
export default __default_export__;
